### ISSUE TITLE
Error Compiling on Fedora 26 "No rule to make target '2344'"

### ISSUE THREAD

**Issue by amirdagan** [Microsemi/switchtec-kernel#3]
```
[root@FAB3-1-Canister-1 switchtec-kernel]# git branch
* backport_4.12
  master
[root@FAB3-1-Canister-1 switchtec-kernel]# make && make install
make -C /lib/modules/4.12.11-300.fc26.x86_64/build M=$PWD modules
make[1]: Entering directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
  CC [M]  /root/switchtec-kernel/ntb_hw_switchtec.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /root/switchtec-kernel/ntb_hw_switchtec.mod.o
  LD [M]  /root/switchtec-kernel/ntb_hw_switchtec.ko
  CC      /root/switchtec-kernel/switchtec.mod.o
  LD [M]  /root/switchtec-kernel/switchtec.ko
make[1]: Leaving directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
make -C /lib/modules/4.12.11-300.fc26.x86_64/build M=$PWD modules_install
make[1]: Entering directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
  INSTALL /root/switchtec-kernel/ntb_hw_switchtec.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:74
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:81
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL /root/switchtec-kernel/switchtec.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:74
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:81
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.12.11-300.fc26.x86_64
depmod: WARNING: /lib/modules/4.12.11-300.fc26.x86_64/extra/ntb_hw_switchtec.ko needs unknown symbol switchtec_class
make[1]: Leaving directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
[root@FAB3-1-Canister-1 switchtec-kernel]# git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
[root@FAB3-1-Canister-1 switchtec-kernel]# git branch
  backport_4.12
* master
[root@FAB3-1-Canister-1 switchtec-kernel]# make && make install
make -C /lib/modules/4.12.11-300.fc26.x86_64/build M=$PWD modules
make[1]: Entering directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
  CC [M]  /root/switchtec-kernel/ntb_hw_switchtec.o
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_mw_count':
/root/switchtec-kernel/ntb_hw_switchtec.c:202:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c:202:14: note: each undeclared identifier is reported only once for each function it appears in
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_mw_get_align':
/root/switchtec-kernel/ntb_hw_switchtec.c:230:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_mw_set_trans':
/root/switchtec-kernel/ntb_hw_switchtec.c:306:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_peer_spad_read':
/root/switchtec-kernel/ntb_hw_switchtec.c:704:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_peer_spad_write':
/root/switchtec-kernel/ntb_hw_switchtec.c:721:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c: In function 'switchtec_ntb_peer_spad_addr':
/root/switchtec-kernel/ntb_hw_switchtec.c:741:14: error: 'NTB_DEF_PEER_IDX' undeclared (first use in this function); did you mean 'NOP_DS_PREFIX'?
  if (pidx != NTB_DEF_PEER_IDX)
              ^~~~~~~~~~~~~~~~
              NOP_DS_PREFIX
/root/switchtec-kernel/ntb_hw_switchtec.c: At top level:
/root/switchtec-kernel/ntb_hw_switchtec.c:754:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .mw_count  = switchtec_ntb_mw_count,
               ^~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:754:15: note: (near initialization for 'switchtec_ntb_ops.mw_count')
/root/switchtec-kernel/ntb_hw_switchtec.c:755:3: error: 'const struct ntb_dev_ops' has no member named 'mw_get_align'; did you mean 'mw_get_range'?
  .mw_get_align  = switchtec_ntb_mw_get_align,
   ^~~~~~~~~~~~
   mw_get_range
/root/switchtec-kernel/ntb_hw_switchtec.c:755:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .mw_get_align  = switchtec_ntb_mw_get_align,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:755:19: note: (near initialization for 'switchtec_ntb_ops.mw_get_range')
/root/switchtec-kernel/ntb_hw_switchtec.c:756:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .mw_set_trans  = switchtec_ntb_mw_set_trans,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:756:19: note: (near initialization for 'switchtec_ntb_ops.mw_set_trans')
/root/switchtec-kernel/ntb_hw_switchtec.c:757:3: error: 'const struct ntb_dev_ops' has no member named 'peer_mw_count'; did you mean 'mw_count'?
  .peer_mw_count  = switchtec_ntb_peer_mw_count,
   ^~~~~~~~~~~~~
   mw_count
/root/switchtec-kernel/ntb_hw_switchtec.c:757:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .peer_mw_count  = switchtec_ntb_peer_mw_count,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:757:20: note: (near initialization for 'switchtec_ntb_ops.mw_clear_trans')
/root/switchtec-kernel/ntb_hw_switchtec.c:758:3: error: 'const struct ntb_dev_ops' has no member named 'peer_mw_get_addr'; did you mean 'peer_db_addr'?
  .peer_mw_get_addr = switchtec_ntb_peer_mw_get_addr,
   ^~~~~~~~~~~~~~~~
   peer_db_addr
/root/switchtec-kernel/ntb_hw_switchtec.c:758:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .peer_mw_get_addr = switchtec_ntb_peer_mw_get_addr,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:758:22: note: (near initialization for 'switchtec_ntb_ops.link_is_up')
/root/switchtec-kernel/ntb_hw_switchtec.c:759:17: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .link_is_up  = switchtec_ntb_link_is_up,
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:759:17: note: (near initialization for 'switchtec_ntb_ops.link_is_up')
/root/switchtec-kernel/ntb_hw_switchtec.c:775:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .peer_spad_read  = switchtec_ntb_peer_spad_read,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:775:21: note: (near initialization for 'switchtec_ntb_ops.peer_spad_read')
/root/switchtec-kernel/ntb_hw_switchtec.c:776:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .peer_spad_write = switchtec_ntb_peer_spad_write,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:776:21: note: (near initialization for 'switchtec_ntb_ops.peer_spad_write')
/root/switchtec-kernel/ntb_hw_switchtec.c:777:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .peer_spad_addr  = switchtec_ntb_peer_spad_addr,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/switchtec-kernel/ntb_hw_switchtec.c:777:21: note: (near initialization for 'switchtec_ntb_ops.peer_spad_addr')
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:309: /root/switchtec-kernel/ntb_hw_switchtec.o] Error 1
make[1]: *** [Makefile:1519: _module_/root/switchtec-kernel] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.12.11-300.fc26.x86_64'
make: *** [Makefile:21: modules] Error 2
[root@FAB3-1-Canister-1 switchtec-kernel]#
```

**Comment by kelvin-cao** [comment]
Hi,

I guess you made a typo when trying build on backport_4.12 branch. Please try 'make **&&** make install' instead of 'make **$$** make install'

Thanks,
Kelvin

**Comment by amirdagan** [comment]
Thanks Kevin - I've updated the comment to reflect the correct command line on both master and backport_4.12 branches.

**Comment by lsgunth** [comment]
Hi,

Looks like the backport_4.12 branch mostly worked except for 2 issues and the master branch is not expected to work on a 4.12 kernel (it's for 4.13).

The 2 issues are:
1) You are trying to build a signed kernel without a signature to sign it. I think this is an out of tree extension in Fedora so I'm not sure how it all works but.. you may be able to disable it by disabling EFI_SECURE_BOOT_SIG_ENFORCE in your kernel config. Otherwise see [this answer](https://github.com/andikleen/simple-pt/issues/8#issuecomment-300575114).

2) It looks like you are using the in-kernel switchtec module with the out-of-tree code. You should turn off CONFIG_PCI_SW_SWITCHTEC so that the out-of-tree module is used instead.

Logan
